name: 🛠️ 构建 OnePlus9 Ksu Next SUSFS 内核

on:
  workflow_dispatch:

env:
  KERNEL_WORKSPACE: ${{ github.workspace }}/kernel_workspace
  release: "true"  # 默认设置为 true，表示需要发布
  REPOS_JSON: "repos.oneplus_9.json"  # 动态指定的 JSON 文件路径

jobs:
  parse-config:
    name: "📖 解析配置文件"
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.parse.outputs.repo }}
    steps:
      - name: "📚 检出代码"
        uses: actions/checkout@v3

      - name: "📝 解析指定的 JSON 文件"
        id: parse
        run: |
          echo "repo<<EOF" >> $GITHUB_OUTPUT
          jq '.[]' ${{ env.REPOS_JSON }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  build-kernel:
    name: "🛠️ 构建 KernelSU Next SUSFS"
    runs-on: ubuntu-latest
    needs: parse-config
    steps:
      - name: "🧳 释放构建空间"
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: "⚙️ 配置 Git"
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: "📦 安装依赖"
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3 git curl jq

      - name: "🛠️ 安装 repo 工具"
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: "🔄 初始化 repo 并同步"
        env:
          CPU: ${{ fromJSON(needs.parse-config.outputs.repo).CPU }}
          FEIL: ${{ fromJSON(needs.parse-config.outputs.repo).FEIL }}
        run: |
          mkdir -p $KERNEL_WORKSPACE && cd $KERNEL_WORKSPACE
          repo init -u https://github.com/toraidl/android_kernel_manifest.git -b oneplus/sm8350v_15.0.0_oneplus9pro -m default.xml --depth=1
          repo sync
          rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "没有受保护的导出！"
          rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "没有受保护的导出！"
          sed -i 's/ -dirty//g' kernel_platform/common/scripts/setlocalversion
          sed -i 's/ -dirty//g' kernel_platform/msm-kernel/scripts/setlocalversion

      - name: "🛠️ 设置 KernelSU Next"
        id: setup-ksu
        run: |
          cd $KERNEL_WORKSPACE/kernel_platform
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s next
          cd KernelSU-Next
          KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_OUTPUT
          sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

      - name: "🛠️ 设置 susfs"
        env:
          ANDROID_VERSION: ${{ fromJSON(needs.parse-config.outputs.repo).ANDROID_VERSION }}
          KERNEL_VERSION: ${{ fromJSON(needs.parse-config.outputs.repo).KERNEL_VERSION }}
        run: |
          cd $KERNEL_WORKSPACE
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${ANDROID_VERSION}-${KERNEL_VERSION}
          git clone https://github.com/TheWildJames/kernel_patches.git
          cd kernel_platform
          cp ../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU-Next/
          cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${ANDROID_VERSION}-${KERNEL_VERSION}.patch ./common/
          cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
          cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/

          cd ./KernelSU-Next
          patch -p1 --forward < 10_enable_susfs_for_ksu.patch || true
          cd ../common
          patch -p1 < 50_add_susfs_in_gki-${ANDROID_VERSION}-${KERNEL_VERSION}.patch || true
          cp ../../kernel_patches/69_hide_stuff.patch ./
          patch -p1 -F 3 < 69_hide_stuff.patch
          git add -A && git commit -a -m "构建内核"
          cd ..
          cd ./msm-kernel && git add -A && git commit -a -m "构建内核"
          cd ..

          cp ../kernel_patches/apk_sign.c_fix.patch ./
          patch -p1 -F 3 < apk_sign.c_fix.patch

          cp ../kernel_patches/core_hook.c_fix.patch ./
          patch -p1 --fuzz=3 < ./core_hook.c_fix.patch

          cp ../kernel_patches/selinux.c_fix.patch ./
          patch -p1 -F 3 < selinux.c_fix.patch

      - name: "🛠️ 构建内核"
        env:
          CPUD: ${{ fromJSON(needs.parse-config.outputs.repo).CPUD }}
        run: |
          cd $KERNEL_WORKSPACE
          ./kernel_platform/oplus/build/oplus_build_kernel.sh ${CPUD} gki

      - name: "🛠️ 创建 AnyKernel3"
        run: |
          git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
          rm -rf ./AnyKernel3/.git
          cp $KERNEL_WORKSPACE/kernel_platform/out/msm-kernel-${{ fromJSON(needs.parse-config.outputs.repo).CPUD }}-gki/dist/Image ./AnyKernel3/

      - name: 📤 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3_KernelSU_Next_${{ steps.setup-ksu.outputs.KSUVER }}_${{ fromJSON(needs.parse-config.outputs.repo).FEIL }}
          path: "./AnyKernel3/*"

      - name: "📤 打包"
        env:
          anykernel: "AnyKernel3_KernelSU_Next_${{ steps.setup-ksu.outputs.KSUVER }}_${{ fromJSON(needs.parse-config.outputs.repo).FEIL }}"
        run: |
          cd AnyKernel3/
          zip -q -r "${{ env.anykernel }}.zip" *

      - name: "🧧 创建 GitHub Release"
        uses: softprops/action-gh-release@v2
        if: ${{ env.release == 'true' }}
        with:
          tag_name: "KernelSU-Next-SUSFS-${{ steps.setup-ksu.outputs.KSUVER }}"
          name: "KernelSU Next SUSFS 内核 v${{ steps.setup-ksu.outputs.KSUVER }}"
          generate_release_notes: true
          files: "${{ github.workspace }}/AnyKernel3/AnyKernel3_KernelSU_Next_${{ steps.setup-ksu.outputs.KSUVER }}_${{ fromJSON(needs.parse-config.outputs.repo).FEIL }}.zip"
